### ISSUE TITLE
Transfer to emacs-php group

### ISSUE THREAD

**Issue by Fuco1** [emacs-php/emacs-nette-tester#2]
@zonuexe if you have nothing against we could move this package into the group to make it better visible for users.

I've also developed https://github.com/Fuco1/neon-mode/ which is not a php only project but is mostly used  in php frameworks (nette).  We could transfer that as well.

Cheers!

**Comment by zonuexe** [comment]
Thank you, I welcome this proposal. And I trust you as a developer so I invited you as one of the owner of the organization.

**Comment by Fuco1** [comment]
@zonuexe Thanks!  I'm not sure how this works, if I transfer the ownership now in the settings will I still be able to push to the repository?

I didn't get any invitation, or maybe I don't know where to look :blush: Any hints there?

**Comment by Fuco1** [comment]
(nevermind I got the invitation, I had to visit the org page)
